In [1]:
import numpy as np
import pandas as pd
def Gauss_method(A, b):
    print("Точный метод Гаусса")
    print("A\n", A, "\nb\n", b)
    arr = np.copy(A)
    brr = np.copy(b)
    for k in range(arr.shape[0] - 1):
        #сначала ищем максимальный элемент в столбце
        max_elem = 0
        str = 0
        for i in range (k, arr.shape[0]):
            if abs(arr[i,k]) > abs(max_elem):
                max_elem = arr[i,k]
                str = i
        #меняем строки местами
        change = np.repeat(arr[k], 1)
        arr[k], arr[str] = arr[str], change
        
        change = np.repeat(brr[k], 1)
        brr[k], brr[str] = brr[str], change
        #делим главный элемент на первый коэфициент
        arr[k] = arr[k] / max_elem
        brr[k] = brr[k] / max_elem
        #проходимся по всем строкам, вычитая строки, умноженные на новый коэфициент
        for i in range (k + 1, arr.shape[0]):
            factor = arr[i,k]
            arr[i] = arr[i] - arr[k] * factor
            brr[i] = brr[i] - brr[k] * factor

    #находим аргументы уравнений
    arg = [brr[brr.shape[0] - 1] / (arr[arr.shape[0] - 1, arr.shape[0] - 1])]
    for i in range(arr.shape[0] - 2, -1, -1):
        n = brr[i]
        for j in range(len(arg)):
            n = n - arg[j] * arr[i, arr.shape[0] - 1 - j]
        arg.append(n)
    arg = arg[::-1]
    print("new A\n", arr, "\nnew b\n", brr, "\nsolution\n", np.round(arg))
    
def Gauss_Seidel_method(A, b, eps, res):
    print("Метод простых итераций Зейделя")
    print("A\n", A, "\nb\n", b)
    m = len(A)
    x = [.0 for i in range(m)]
    res["x0"] = x
    converge = False
    pogr = 1.
    k = 1
    iter = 0
    while not converge:
        x_new = np.copy(x)
        for i in range(m):
            s1 = sum(A[i][j] * x_new[j] for j in range(i))
            s2 = sum(A[i][j] * x[j] for j in range(i + 1, m))
            x_new[i] = (b[i] - s1 - s2) / A[i][i]
        pogr = sum(abs(x_new[i] - x[i])  for i in range(m))
        iter += 1
        x = x_new
        res["x" + str(iter)] = x_new
        converge = pogr < eps
    print("solution\n", np.round(x))

In [2]:
A = np.array([[3, 1, 1], [1, 5, 1], [1, 1, 7]])
b = np.array([5, 7, 9])
Gauss_method(A, b)
print()
eps = 1e-6
res = pd.DataFrame()
Gauss_Seidel_method(A, b, eps, res)
res

Точный метод Гаусса
A
 [[3 1 1]
 [1 5 1]
 [1 1 7]]
b
 [5 7 9]
new A
 [[1 0 0]
 [0 1 0]
 [0 0 7]]
new b
 [1 1 7]
solution
 [1. 1. 1.]

Метод простых итераций Зейделя
A
 [[3 1 1]
 [1 5 1]
 [1 1 7]]
b
 [5 7 9]
solution
 [1. 1. 1.]

    x0        x1        x2        x3        x4        x5        x6   x7   x8
0  0.0  1.666667  1.012698  0.995344  0.999258  0.999945  1.000000  1.0  1.0
1  0.0  1.066667  1.018413  1.001820  1.000067  0.999992  0.999998  1.0  1.0
2  0.0  0.895238  0.995556  1.000405  1.000096  1.000009  1.000000  1.0  1.0

In [3]:
eps = 1e-6
i = 3
A = np.identity(i) 
N = np.ones((i,i))
for j in range(1,i):
    A -= np.eye(i, k = j)
    N -= 2*np.eye(i, k = j)
A += eps*N
b = -np.ones(i)
b[-1] += 2
Gauss_method(A, b)
print()
res = pd.DataFrame()
Gauss_Seidel_method(A, b, eps, res)
res

Точный метод Гаусса
A
 [[ 1.000001e+00 -1.000001e+00 -1.000001e+00]
 [ 1.000000e-06  1.000001e+00 -1.000001e+00]
 [ 1.000000e-06  1.000000e-06  1.000001e+00]]
b
 [-1. -1.  1.]
new A
 [[ 1.       -1.       -1.      ]
 [ 0.        1.       -0.999998]
 [ 0.        0.        1.000004]]
new b
 [-0.999999 -0.999997  1.000003]
solution
 [0. 0. 1.]

Метод простых итераций Зейделя
A
 [[ 1.000001e+00 -1.000001e+00 -1.000001e+00]
 [ 1.000000e-06  1.000001e+00 -1.000001e+00]
 [ 1.000000e-06  1.000000e-06  1.000001e+00]]
b
 [-1. -1.  1.]
solution
 [-0. -0.  1.]

    x0        x1        x2            x3            x4            x5
0  0.0 -0.999999 -0.999996  3.999982e-06  9.999830e-07 -7.000060e-12
1  0.0 -0.999998  0.000003  9.999880e-07 -6.000083e-12 -9.999769e-13
2  0.0  1.000001  1.000000  9.999990e-01  9.999990e-01  9.999990e-01